baseurl = "https://yord.io/"
languageCode = "en-us"
theme = "hello-friend-ng"
[author]
name = "Yordi Verkroost"
[languages.en]
copyright = ""
image = "avatar.png"
keywords = ""
readOtherPosts = "Read other posts"
subtitle = "Living the Digital World"
title = "Yordi Verkroost"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "yordI/O"
[[menu.main]]
name = "Tweets"
url = "https://www.twitter.com/yordiverkroost"
weight = 2
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 1
[params]
contentTypeName = "posts"
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
defaultTheme = "light"
description = "yordI/O | Living the Digital World"
disableReadOtherPosts = false
images = [""]
keywords = "homepage, blog"
[[params.social]]
name = "twitter"
url = "https://twitter.com/yordiverkroost"
[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/yordiverkroost/"
[[params.social]]
name = "github"
url = "https://github.com/Froodooo"
