baseurl = "https://yord.io/"
languageCode = "en-us"
theme = "hello-friend-ng"

[author]
  name = "Yordi Verkroost"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "yordI/O | Living the Digital World"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/yordiverkroost"
  
  [[params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/yordiverkroost/"
  
  [[params.social]]
    name = "github"
    url  = "https://github.com/Froodooo"

[languages]
  [languages.en]
    title = "Yordi Verkroost"
    subtitle = "Living the Digital World"
    image = "avatar.png"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "yordI/O"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"